import '../models/user.dart';
import '../models/course.dart';
import '../models/registration.dart';
import '../models/announcement.dart';

class MockData {
  static List<User> initialUsers = [
    User(
      id: 'usr-admin-1',
      email: 'admin@alagappa.ac.in',
      name: 'Dr. M. Shanmugam (Super Admin)',
      role: UserRole.SUPER_ADMIN,
      departmentId: 'dept-cse',
      phone: '+91 9842100001',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    ),
    User(
      id: 'usr-deptadmin-1',
      email: 'cs_admin@alagappa.ac.in',
      name: 'Dr. A. Nagarajan (CSE Admin)',
      role: UserRole.DEPT_ADMIN,
      departmentId: 'dept-cse',
      phone: '+91 9842100002',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    ),
    User(
      id: 'usr-faculty-1',
      email: 'ramanathan@alagappa.ac.in',
      name: 'Dr. R. Ramanathan',
      role: UserRole.FACULTY,
      departmentId: 'dept-cse',
      phone: '+91 9842100003',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    ),
    User(
      id: 'usr-student-1',
      email: 'student@alagappa.ac.in',
      name: 'K. Vijaykumar',
      role: UserRole.STUDENT,
      registerNumber: '2024101001',
      departmentId: 'dept-mgt',
      phone: '+91 9842199999',
      cgpa: 8.85,
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    ),
  ];

  static List<Course> initialCourses = [
    Course(
      id: 'crs-101',
      code: 'NME-CSE-101',
      title: 'Python Programming for Data Analysis',
 description: 'Learn fundamental Python scripting, NumPy, Pandas, and Data Visualization techniques tailored for all non-major disciplines.',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science',
      facultyId: 'usr-faculty-1',
      facultyName: 'Dr. R. Ramanathan',
      credits: 3,
      semester: 3,
      totalSeats: 60,
      filledSeats: 42,
      venue: 'Lab 3, Science Block A',
      scheduleDays: 'Mon, Wed, Fri',
      scheduleTime: '10:00 AM - 11:00 AM',
      difficulty: 'Beginner',
      prerequisites: 'Basic Computer Literacy',
      rating: 4.9,
      status: 'APPROVED',
    ),
    Course(
      id: 'crs-201',
      code: 'NME-MGT-201',
      title: 'Digital Marketing & Social Media Strategy',
      description: 'Comprehensive guide to SEO, Google Analytics, content strategy, brand building, and social media ad execution.',
      departmentId: 'dept-mgt',
      departmentName: 'Department of Management Studies',
      facultyId: 'usr-faculty-1',
      facultyName: 'Dr. S. Kanthimathi',
      credits: 3,
      semester: 3,
      totalSeats: 50,
      filledSeats: 50, // FULL
      venue: 'Seminar Hall 2, Management Tower',
      scheduleDays: 'Tue, Thu',
      scheduleTime: '02:00 PM - 03:30 PM',
      difficulty: 'Intermediate',
      prerequisites: 'None',
      rating: 4.8,
      status: 'APPROVED',
    ),
    Course(
      id: 'crs-102',
      code: 'NME-CSE-102',
      title: 'Cyber Security & Personal Privacy',
      description: 'Protecting personal identity online, network security basics, safe web browsing, encryption, and threat prevention.',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science',
      facultyId: 'usr-faculty-1',
      facultyName: 'Prof. M. Suresh',
      credits: 3,
      semester: 3,
      totalSeats: 45,
      filledSeats: 41, // Amber seat
      venue: 'Room 204, Science Block A',
      scheduleDays: 'Mon, Wed',
      scheduleTime: '02:00 PM - 03:30 PM',
      difficulty: 'Beginner',
      prerequisites: 'None',
      rating: 4.7,
      status: 'APPROVED',
    ),
    Course(
      id: 'crs-105',
      code: 'NME-COM-105',
      title: 'Financial Literacy & Mutual Fund Investment',
      description: 'Practical guide to budgeting, stock market basics, tax planning, mutual funds, and long-term personal wealth management.',
      departmentId: 'dept-com',
      departmentName: 'Department of Commerce',
      facultyId: 'usr-faculty-1',
      facultyName: 'Dr. V. Meenakshi',
      credits: 2,
      semester: 3,
      totalSeats: 80,
      filledSeats: 25,
      venue: 'Auditorium B, Commerce Complex',
      scheduleDays: 'Tue, Thu',
      scheduleTime: '10:00 AM - 11:30 AM',
      difficulty: 'Beginner',
      prerequisites: 'None',
      rating: 4.95,
      status: 'APPROVED',
    ),
    Course(
      id: 'crs-301',
      code: 'NME-TAM-101',
      title: 'Applied Tamil Literature & Folk Art Heritage (தமிழ்க் கலைகள்)',
      description: 'Exploration of classical Tamil poetry, traditional music, folk dance, and cultural history of Tamil Nadu.',
      departmentId: 'dept-tam',
      departmentName: 'Department of Tamil',
      facultyId: 'usr-faculty-1',
      facultyName: 'Dr. P. Thirunavukkarasu',
      credits: 3,
      semester: 3,
      totalSeats: 50,
      filledSeats: 18,
      venue: 'Tamil Sangam Hall, Humanities Block',
      scheduleDays: 'Mon, Fri',
      scheduleTime: '03:30 PM - 05:00 PM',
      difficulty: 'Beginner',
      prerequisites: 'Basic Tamil Reading',
      rating: 4.9,
      status: 'APPROVED',
    ),
  ];

  static List<Registration> initialRegistrations = [
    Registration(
      id: 'reg-901',
      registrationNo: 'NME-2026-88101',
      studentId: 'usr-student-1',
      courseId: 'crs-101',
      status: 'CONFIRMED',
      registeredAt: '2026-08-01T10:00:00.000Z',
      qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=NME-2026-88101',
    ),
  ];

  static List<Announcement> initialAnnouncements = [
    Announcement(
      id: 'ann-1',
      title: 'Phase II NME Registration Open!',
      content: 'All 3rd Semester UG Students are requested to finalize Non-Major Elective course selections before Friday 5:00 PM.',
      sender: 'NME Nodal Officer, Alagappa University',
      timestamp: '2026-08-02 09:00 AM',
      category: 'URGENT',
    ),
    Announcement(
      id: 'ann-2',
      title: 'Govt. Tuition Fee Waiver Guidelines',
      content: 'Students eligible under TN Higher Education Fee Waiver Scheme must upload CGPA details in the Credit Ledger.',
      sender: 'Dean of Academic Affairs',
      timestamp: '2026-08-01 02:30 PM',
      category: 'NOTICE',
    ),
  ];
}
