class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'app_title': 'Alagappa University NME Portal',
      'university_name': 'Alagappa University, Karaikudi',
      'nme_subtitle': 'Non-Major Elective Real-Time Portal',
      'login': 'Login',
      'logout': 'Logout',
      'email': 'Email Address',
      'password': 'Password',
      'quick_login_roles': 'Quick Demo Sign In as:',
      'super_admin': 'Super Admin',
      'dept_admin': 'Dept Admin',
      'faculty': 'Faculty',
      'student': 'Student',
      'courses': 'NME Courses',
      'my_dashboard': 'Dashboard',
      'timetable': 'Timetable',
      'credit_ledger': 'Credit Ledger',
      'search_courses': 'Search course code, title or department...',
      'filter_department': 'All Departments',
      'semester': 'Semester',
      'seats_available': 'Seats Available',
      'available': 'AVAILABLE',
      'few_left': 'FEW LEFT',
      'full_waitlist': 'FULL / WAITLIST',
      'register': 'Register Now',
      'registered': 'Enrolled',
      'waitlist': 'Join Waitlist',
      'waitlisted': 'Waitlisted',
      'conflict_warning': 'Timetable Slot Conflict Detected!',
      'view_details': 'View Syllabus & Schedule',
      'qr_slip': 'Digital Registration Pass',
      'attendance_scanner': 'QR Attendance Scanner',
      'scan_qr': 'Scan Student QR Code',
      'ai_advisor': 'AI Course Advisor',
      'certificate': 'Digital NME Gold Certificate',
      'fee_waiver': 'Govt. Tamil Nadu Tuition Fee Waiver Active',
      'announcements': 'University Broadcasts',
      'system_health': 'System Health & Latency',
      'tamil_switch': 'தமிழ்',
      'english_switch': 'English',
    },
    'ta': {
      'app_title': 'அழகப்பா பல்கலைக்கழக NME தளம்',
      'university_name': 'அழகப்பா பல்கலைக்கழகம், காரைக்குடி',
      'nme_subtitle': 'சார்பற்ற விருப்பப் பாடத் தேர்வு மையம்',
      'login': 'உள்நுழை',
      'logout': 'வெளியேறு',
      'email': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'quick_login_roles': 'மாதிரி உள்நுழைவு தேர்வு:',
      'super_admin': 'தலைமை நிர்வாகி',
      'dept_admin': 'துறை நிர்வாகி',
      'faculty': 'பேராசிரியர்',
      'student': 'மாணவர்',
      'courses': 'NME விருப்பப் பாடங்கள்',
      'my_dashboard': 'என் முகப்புப் பக்கம்',
      'timetable': 'கால அட்டவணை',
      'credit_ledger': 'மதிப்பெண் & கட்டண விவரம்',
      'search_courses': 'பாடக் குறியீடு, தலைப்பு தேடுக...',
      'filter_department': 'அனைத்துத் துறைகள்',
      'semester': 'பருவம்',
      'seats_available': 'இடங்கள் உள்ளன',
      'available': 'இடங்கள் உள்ளன',
      'few_left': 'சில இடங்களே உள்ளன',
      'full_waitlist': 'முழுமை / காத்திருப்பு',
      'register': 'பதிவு செய்',
      'registered': 'பதிவு செய்யப்பட்டது',
      'waitlist': 'காத்திருப்போர் பட்டியல்',
      'waitlisted': 'காத்திருப்பில் உள்ளது',
      'conflict_warning': 'நேர மோதல் கண்டறியப்பட்டது!',
      'view_details': 'பாடத்திட்டம் & அட்டவணை',
      'qr_slip': 'டிஜிட்டல் பதிவுச் சீட்டு',
      'attendance_scanner': 'QR வருகைப் பதிவு ஸ்கேனர்',
      'scan_qr': 'மாணவர் QR குறியீட்டை ஸ்கேன் செய்க',
      'ai_advisor': 'செயற்கை நுண்ணறிவு பாட ஆலை',
      'certificate': 'டிஜிட்டல் தங்கச் சான்றிதழ்',
      'fee_waiver': 'தமிழக அரசு இலவசக் கல்விச் சலுகை',
      'announcements': 'பல்கலைக்கழக அறிவிப்புகள்',
      'system_health': 'கணினி நிலைமை & தாமதம்',
      'tamil_switch': 'தமிழ்',
      'english_switch': 'English',
    }
  };

  static String get(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
